# Generated by Django 2.0.1 on 2018-01-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_time',
            new_name='pub_date',
        ),
    ]
